export const WITHDRWAL_REQUEST = "WITHDRWAL_REQUEST";
export const WITHDRWAL_SUCCESS = "WITHDRWAL_SUCCESS";
export const WITHDRWAL_FAILURE = "WITHDRWAL_FAILURE";


export const WITHDRWAL_PROCEED_REQUEST = "WITHDRWAL_PROCEED_REQUEST";
export const WITHDRWAL_PROCEED_SUCCESS = "WITHDRWAL_PROCEED_SUCCESS";
export const WITHDRWAL_PROCEED_FAILURE = "WITHDRWAL_PROCEED_FAILURE";



export const GET_WITHDRWAL_HISTORY_REQUEST = "GET_WITHDRWAL_HISTORY_REQUEST";
export const GET_WITHDRWAL_HISTORY_SUCCESS = "GET_WITHDRWAL_HISTORY_SUCCESS";
export const GET_WITHDRWAL_HISTORY_FAILURE = "GET_WITHDRWAL_HISTORY_FAILURE";


export const GET_WITHDRWAL_REQUEST_REQUEST = "GET_WITHDRWAL_REQUEST_REQUEST";
export const GET_WITHDRWAL_REQUEST_SUCCESS = "GET_WITHDRWAL_REQUEST_SUCCESS";
export const GET_WITHDRWAL_REQUEST_FAILURE = "GET_WITHDRWAL_REQUEST_FAILURE";


export const ADD_PAYMENT_DETAILS_REQUEST = "ADD_PAYMENT_DETAILS_REQUEST";
export const ADD_PAYMENT_DETAILS_SUCCESS = "ADD_PAYMENT_DETAILS_SUCCESS";
export const ADD_PAYMENT_DETAILS_FAILURE = "ADD_PAYMENT_DETAILS_FAILURE";



export const GET_PAYMENT_DETAILS_REQUEST = "GET_PAYMENT_DETAILS_REQUEST";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";
export const GET_PAYMENT_DETAILS_FAILURE = "GET_PAYMENT_DETAILS_FAILURE";
